FROM python:3

WORKDIR /home/

COPY requirements.txt ./



RUN pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir -r requirements.txt

COPY *.py ./

CMD ["python", "./start_pipe.py"]