FROM python:3

WORKDIR /usr/src

COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip \ 
&& pip install --no-cache-dir -r /usr/src/requirements.txt

# RUN pip install --no-cache-dir --upgrade pip \
#   && pip install --no-cache-dir -r /usr/src/requirements.txt

COPY *.py ./
COPY ./ccr* ./

CMD ["python", "./start_pipe.py"]

