FROM python:3

WORKDIR /usr/src

COPY requirments.txt ./

RUN pip install --no-cache-dir --upgrade pip

# RUN pip install --no-cache-dir --upgrade pip \
#   && pip install --no-cache-dir -r /usr/src/requirements.txt

COPY *.py ./
COPY /var/lib/jenkins/workspace/ci-monitoring/ccr/ccr* ./

CMD ["python", "./start_pipe.py"]

